---
- name: "Setup development environment"
  hosts: web:&development
  become: yes
  remote_user: vagrant
  gather_facts: True

  roles:
  - { role: common, tags: [common] }
  - { role: geerlingguy.nginx, tags: [nginx] }
  - { role: geerlingguy.php, tags: [php] }
  - { role: geerlingguy.mysql, tags: [mysql] }

  tasks:
  - name: Ensure phpMyAdmin is installed
    apt:
      name: phpmyadmin
      state: present
      update_cache: yes
