---
- name: Provision remote servers
  hosts: web:&{{ env }}
  remote_user: root

  pre_tasks:
  - name: Setup users
    user:
      name: "{{ item.name }}"
      state: present
      shell: /bin/bash
      group: "{{ item.groups[0] }}"
      groups: "{{ item.groups | join(',') }}"
      generate_ssh_key: yes
      createhome: yes
    with_items:
    - "{{ users }}"

  - name: Set authorized key for users
    authorized_key:
      user: "{{ item.0.name }}"
      key: "{{ item.1 }}"
    with_subelements:
    - "{{ users | default([]) }}"
    - keys

  - name: Create the directory www_root if it doesn't exist
    file:
      path: "{{ www_root }}"
      state: directory
      owner: "{{ web_user }}"
      group: "{{ web_group }}"
      mode: 0755

  roles:
  - { role: geerlingguy.apache, tags: [apache] }
