---
php_version: "7.0"
php_webserver_daemon: "nginx"
php_fpm_daemon: "php7.0-fpm"
php_enable_php_fpm: true
php_fpm_listen: "/run/php/php7.0-fpm.sock"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5
php_memory_limit: "128M"
php_max_execution_time: "3600"
php_upload_max_filesize: "128M"
php_post_max_size: "128M"
php_date_timezone: "{{ ntp_timezone }}"
php_packages:
- php7.0-common
- php7.0-cli
- php7.0-dev
- php7.0-fpm
- php7.0-gd
- php7.0-mbstring
- php7.0-pdo
- php7.0-xml
- php7.0-zip
