---
nginx_access_log: "/var/log/nginx/access.log main buffer=32k"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_remove_default_vhost: true
nginx_sendfile: "off"
nginx_vhosts:
- listen: "80"
  server_name: "_"
  index: "index.html index.htm index.php"
  extra_parameters: |
    location /phpmyadmin {
      root /usr/share;
      index index.php index.html index.htm;
      location ~ ^/phpmyadmin/(.+\.php)$ {
        try_files $uri =404;
        root /usr/share;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 3600;
        include fastcgi_params;
      }
      location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
        root /usr/share;
      }
    }
- listen: "80"
  server_name: "example.com"
  filename: "example.com.conf"
  root: "/home/vagrant/www/example.com"
  index: "index.html index.htm index.php"
  charset: "utf-8"
  extra_parameters: |
    location / {
      try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \.php$ {
      fastcgi_split_path_info ^(.+\.php)(/.+)$;
      fastcgi_pass unix:/run/php/php7.0-fpm.sock;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      fastcgi_read_timeout 3600;
      include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
      deny all;
    }

php_version: "7.0"
php_webserver_daemon: "nginx"
php_fpm_daemon: "php7.0-fpm"
php_memory_limit: "128M"
php_max_execution_time: "300"
php_upload_max_filesize: "128M"
php_post_max_size: "128M"
php_date_timezone: "{{ ntp_timezone }}"
php_packages:
- php7.0-common
- php7.0-cli
- php7.0-dev
- php7.0-fpm
- php7.0-gd
- php7.0-mbstring
- php7.0-pdo
- php7.0-xml
- php7.0-zip

mysql_root_password: root
mysql_packages:
- mysql-server
- python-mysqldb
mysql_replication_role: "master"
mysql_replication_master: "{{ groups['development'][0] }}"
